version: "3.3"

services:
  httpd:
    build:
      context: .
      dockerfile: ./etc/httpd.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/wordpress
    depends_on:
      - phpfpm

  phpfpm:
    build:
      context: .
      dockerfile: ./etc/phpfpm.Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - ./wordpress:/var/www/wordpress
      - ./etc/php/fpm.php.ini:/usr/local/etc/php/conf.d/fpm.php.ini
      - ./etc/php/xdebug.php.ini:/usr/local/etc/php/conf.d/xdebug.php.ini
    depends_on:
      - db

  wpcli:
    build:
      context: .
      dockerfile: ./etc/wpcli.Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    environment:
      - XDEBUG_TRIGGER
    volumes:
      - ./wordpress:/var/www/wordpress
      - ./etc/php/cli.php.ini:/usr/local/etc/php/conf.d/cli.php.ini
      - ./etc/php/xdebug.php.ini:/usr/local/etc/php/conf.d/xdebug.php.ini
    depends_on:
      - db

  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: app
    volumes:
      - ./etc/php/pma.php.ini:/usr/local/etc/php/conf.d/pma.php.ini
    depends_on:
      - db

  db:
    image: mariadb:latest
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app

volumes:
  mysqldata:
